version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 192.168.10.2



  pgadmin:
    container_name: pgadmin
    image: johnconnor2023/pgadmin4-4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      mynetwork:

  agendapyd:
    image: johnconnor2023/agendapyd
    networks:
      mynetwork:



networks:
  mynetwork:
    ipam:
      config:
        - subnet: 192.168.10.0/24
